apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: teamspeak
    project: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  serviceName: teamspeak
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
      project: teamspeak
  template:
    metadata:
      labels:
        app: teamspeak
        project: teamspeak
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - env:
            - name: TS3SERVER_DB_HOST
              value: teamspeak-mariadb
            - name: TS3SERVER_DB_NAME
              value: teamspeak
            - name: TS3SERVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: teamspeak.user.teamspeak.mariadb
            - name: TS3SERVER_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: teamspeak.user.teamspeak.mariadb
            - name: TS3SERVER_DB_PLUGIN
              value: ts3db_mariadb
            - name: TS3SERVER_DB_SQLCREATEPATH
              value: create_mariadb
            - name: TS3SERVER_DB_WAITUNTILREADY
              value: "30"
            - name: TS3SERVER_LICENSE
              value: accept
          image: teamspeak:3.13.7
          name: teamspeak
          ports:
            - containerPort: 9987
              protocol: UDP
              name: voice
            - containerPort: 10011
              name: serverquey
            - containerPort: 30033
              name: filetransfer
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /var/ts3server
              name: ts-data
        - name: metrics-exporter
          image: denniswitt/ts3exporter:1.0
          env:
            - name: ENABLE_CHANNEL_METRICS
              value: "1"
            - name: IGNORE_FLOOD_LIMITS
              value: "1"
            - name: SERVERQUERY_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: teamspeak-metrics-user
            - name: SERVERQUERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: teamspeak-metrics-user
          ports:
            - containerPort: 9189
              name: metrics
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      restartPolicy: Always
      volumes:
        - name: ts-data
          persistentVolumeClaim:
            claimName: ts-data
