apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: teamspeak
  namespace: teamspeak
  labels:
    app: teamspeak
    project: teamspeak
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  jobLabel: teamspeak
  namespaceSelector:
    matchNames:
      - teamspeak
  selector:
    matchLabels:
      app: teamspeak
      project: teamspeak
