apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamspeak
    project: teamspeak
  name: teamspeak-external
  namespace: teamspeak
spec:
  type: NodePort
  ports:
    - name: voice
      port: 9987
      protocol: UDP
      targetPort: voice
      nodePort: 32492
  selector:
    app: teamspeak
    project: teamspeak
