apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamspeak
    project: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  ports:
    - name: ts
      port: 9987
      protocol: UDP
      targetPort: 9987
    - name: tsquery
      port: 10011
      targetPort: 10011
    - name: file
      port: 30033
      targetPort: 30033
  selector:
    app: teamspeak
    project: teamspeak
