apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamspeak
    project: teamspeak
  name: teamspeak
  namespace: teamspeak
spec:
  ports:
    - name: voice
      port: 9987
      protocol: UDP
      targetPort: 9987
    - name: serverquery
      port: 10011
      targetPort: 10011
    - name: filetransfer
      port: 30033
      targetPort: 30033
    - name: metrics
      port: 9189
      targetPort: 9189
  selector:
    app: teamspeak
    project: teamspeak
