apiVersion: v1
kind: ConfigMap
metadata:
  name: config.teamspeak.mariadb
  namespace: teamspeak
data:
  UMASK: "0660"
  UMASK_DIR: "0750"

---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: teamspeak-mariadb
  namespace: teamspeak
  labels:
    app: mariadb
    project: teamspeak
spec:
  rootPasswordSecretKeyRef:
    name: root.user.teamspeak.mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.11.3"

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    storageClassName: hcloud-volumes
    accessModes:
      - ReadWriteOnce
  volumes:
    - name: tmp
      emptyDir: {}
  volumeMounts:
    - name: tmp
      mountPath: /tmp

  myCnf: |
    [mysqld]
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: config.teamspeak.mariadb

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  livenessProbe:
    exec:
      command:
        - bash
        - -c
        - mysql -u root -p${MARIADB_ROOT_PASSWORD} -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5

  readinessProbe:
    exec:
      command:
        - bash
        - -c
        - mysql -u root -p${MARIADB_ROOT_PASSWORD} -e "SELECT 1;"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5

  metrics:
    exporter:
      image:
        repository: prom/mysqld-exporter
        tag: "v0.14.0"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: k8s
      interval: 10s
      scrapeTimeout: 10s

  service:
    type: ClusterIP
