apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb
    project: teamspeak
  name: db
  namespace: personal
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      project: teamspeak
  template:
    metadata:
      labels:
        app: mariadb
        project: teamspeak
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: teamspeak
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mariadb:10.8.3-jammy
          name: mariadb
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
            - mountPath: /var/run/mysqld
              name: db-socket
      restartPolicy: Always
      volumes:
        - name: db-data
          hostPath:
            path: /var/lib/mysql
        - name: db-socket
          hostPath:
            path: /var/run/mysqld
