apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb
    project: teamspeak
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
