apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: teamspeak
  name: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teamspeak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: teamspeak
    spec:
      containers:
        - env:
            - name: TS3SERVER_DB_HOST
              value: db
            - name: TS3SERVER_DB_NAME
              value: teamspeak
            - name: TS3SERVER_DB_PASSWORD
              value: example
            - name: TS3SERVER_DB_PLUGIN
              value: ts3db_mariadb
            - name: TS3SERVER_DB_SQLCREATEPATH
              value: create_mariadb
            - name: TS3SERVER_DB_USER
              value: root
            - name: TS3SERVER_DB_WAITUNTILREADY
              value: "30"
            - name: TS3SERVER_LICENSE
              value: accept
          image: teamspeak:3.13.7
          name: teamspeak
          ports:
            - containerPort: 9987
              protocol: UDP
            - containerPort: 10011
            - containerPort: 30033
          resources: {}
          volumeMounts:
            - mountPath: /var/ts3server
              name: ts-data
      restartPolicy: Always
      volumes:
        - name: ts-data
          persistentVolumeClaim:
            claimName: ts-data
status: {}
