apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: teamspeak
spec:
  mariaDbRef:
    name: teamspeak-mariadb
  passwordSecretKeyRef:
    name: teamspeak.user.teamspeak.mariadb
    key: password
  maxUserConnections: 20
