apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: teamspeak
    project: teamspeak
  name: ts-data
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
