{
 "title": "Teamspeak 3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "virtualserver",
    "query": "label_values(ts3_serverinfo_online, virtualserver)"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Online Virtual Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ts3_serverinfo_online)" }
   ]
  },
  {
   "title": "Channels Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ts3_serverinfo_channels_online{virtualserver=~\"${virtualserver}\"})"
    }
   ]
  },
  {
   "title": "Permanent Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ts3_channel_permanent{virtualserver=~\"${virtualserver}\"})"
    },
    {}
   ]
  },
  {
   "title": "Password Protected Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ts3_channel_password{virtualserver=~\"${virtualserver}\"})"
    },
    {}
   ]
  },
  {
   "title": "Unencrypted Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ts3_channel_unencrypted{virtualserver=~\"${virtualserver}\"})"
    },
    {}
   ]
  },
  {
   "title": "Exporter Error Rate (last 5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(ts3_exporter_data_model_refresh_errors_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime in Seconds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "repeat": "virtualserver",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ts3_serverinfo_uptime{virtualserver=~\"${virtualserver}\"}",
     "legendFormat": "{{virtualserver}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ts3_serverinfo_control_bytes_sent_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} control bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_control_bytes_received_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} control bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_file_transfer_bytes_sent_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} file transfer bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_file_transfer_bytes_received_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} file transfer bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_keepalive_bytes_sent_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} keepalive bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_keepalive_bytes_received_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} keepalive bytes received"
    },
    {
     "expr": "rate(ts3_serverinfo_speech_bytes_sent_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} speech bytes send"
    },
    {
     "expr": "rate(ts3_serverinfo_speech_bytes_received_total{virtualserver=~\"${virtualserver}\"}[5m])",
     "legendFormat": "{{virtualserver}} speech bytes received"
    }
   ]
  },
  {
   "title": "Clients online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (virtualserver) (ts3_serverinfo_query_clients_online{virtualserver=~\"${virtualserver}\"})",
     "legendFormat": "{{virtualserver}} QueryClients"
    },
    {
     "expr": "max by (virtualserver) (ts3_serverinfo_clients_online{virtualserver=~\"${virtualserver}\"} - ts3_serverinfo_query_clients_online{virtualserver=~\"${virtualserver}\"})",
     "legendFormat": "{{virtualserver}} Clients"
    }
   ]
  },
  {
   "title": "Clients in Channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ts3_channel_clients_online{virtualserver=~\"${virtualserver}\"}",
     "legendFormat": "{{channel}}"
    }
   ]
  }
 ]
}