version: '3.8'
services:
  teamspeak:
    image: teamspeak:3.13.7
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: example
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - ts_data:/var/ts3server/
  db:
    image: mariadb:10.8.3-jammy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: teamspeak
    volumes:
      - db_data:/var/lib/mysql

volumes:
  ts_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/ts3server
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/ts3db